/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mojica.Api
 * OpenAPI spec version: 1.0
 */
import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

export const getPostImagesMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/images",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};
export const getImageMock = () => [getPostImagesMockHandler()];
