/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mojica.Api
 * OpenAPI spec version: 1.0
 */
import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import { getPostImagesResponseMock } from "./image.faker";

export { getPostImagesResponseMock } from "./image.faker";

export const getPostImagesMockHandler = (
  overrideResponse?:
    | ArrayBuffer
    | ((
        info: Parameters<Parameters<typeof http.post>[1]>[0],
      ) => Promise<ArrayBuffer> | ArrayBuffer),
  options?: RequestHandlerOptions,
) => {
  return http.post(
    "*/images",
    async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
      const binaryBody =
        overrideResponse !== undefined
          ? typeof overrideResponse === "function"
            ? await overrideResponse(info)
            : overrideResponse
          : getPostImagesResponseMock();
      return HttpResponse.arrayBuffer(
        binaryBody instanceof ArrayBuffer ? binaryBody : new ArrayBuffer(0),
        { status: 200, headers: { "Content-Type": "image/png" } },
      );
    },
    options,
  );
};
export const getImageMock = () => [getPostImagesMockHandler()];
