/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mojica.Api
 * OpenAPI spec version: 1.0
 */
import { faker } from "@faker-js/faker";

export const getPostImagesResponseMock = (): ArrayBuffer =>
  new ArrayBuffer(faker.number.int({ min: 1, max: 64 }));
