/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mojica.Api
 * OpenAPI spec version: 1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  ApiErrorResponse,
  ApiValidationErrorResponse,
  ImageGenerationRequestDto,
} from "../../../models";

import { customInstance } from "../../mutator/custom-instance";
import type { ErrorType } from "../../mutator/custom-instance";

export const postImages = (
  imageGenerationRequestDto: ImageGenerationRequestDto,
  signal?: AbortSignal,
) => {
  return customInstance<Blob>({
    url: `/images`,
    method: "POST",
    headers: { "Content-Type": "application/json" },
    data: imageGenerationRequestDto,
    responseType: "blob",
    signal,
  });
};

export const getPostImagesMutationOptions = <
  TError = ErrorType<ApiErrorResponse | ApiValidationErrorResponse>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof postImages>>,
    TError,
    { data: ImageGenerationRequestDto },
    TContext
  >;
}): UseMutationOptions<
  Awaited<ReturnType<typeof postImages>>,
  TError,
  { data: ImageGenerationRequestDto },
  TContext
> => {
  const mutationKey = ["postImages"];
  const { mutation: mutationOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey } };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postImages>>,
    { data: ImageGenerationRequestDto }
  > = (props) => {
    const { data } = props ?? {};

    return postImages(data);
  };

  return { mutationFn, ...mutationOptions };
};

export type PostImagesMutationResult = NonNullable<
  Awaited<ReturnType<typeof postImages>>
>;
export type PostImagesMutationBody = ImageGenerationRequestDto;
export type PostImagesMutationError = ErrorType<
  ApiErrorResponse | ApiValidationErrorResponse
>;

export const usePostImages = <
  TError = ErrorType<ApiErrorResponse | ApiValidationErrorResponse>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof postImages>>,
      TError,
      { data: ImageGenerationRequestDto },
      TContext
    >;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof postImages>>,
  TError,
  { data: ImageGenerationRequestDto },
  TContext
> => {
  return useMutation(getPostImagesMutationOptions(options), queryClient);
};
