/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mojica.Api
 * OpenAPI spec version: 1.0
 */

export interface ApiErrorResponse {
  /** @nullable */
  code?: string | null;
  /** @nullable */
  message?: string | null;
}
