/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mojica.Api
 * OpenAPI spec version: 1.0
 */

export interface ApiValidationFieldError {
  /** @nullable */
  field?: string | null;
  /** @nullable */
  message?: string | null;
}
