/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mojica.Api
 * OpenAPI spec version: 1.0
 */

export interface ImageGenerationRequestDto {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  text?: string | null;
  /** @nullable */
  foregroundCharacter?: string | null;
  /** @nullable */
  foregroundColor?: string | null;
  /** @nullable */
  backgroundCharacter?: string | null;
  /** @nullable */
  backgroundColor?: string | null;
}
