/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Mojica.Api
 * OpenAPI spec version: 1.0
 */
import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

export const getGetHealthMockHandler = (
  overrideResponse?:
    | void
    | ((
        info: Parameters<Parameters<typeof http.get>[1]>[0],
      ) => Promise<void> | void),
  options?: RequestHandlerOptions,
) => {
  return http.get(
    "*/health",
    async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
      if (typeof overrideResponse === "function") {
        await overrideResponse(info);
      }

      return new HttpResponse(null, { status: 200 });
    },
    options,
  );
};
export const getMojicaApiMock = () => [getGetHealthMockHandler()];
