namespace Mojica.Api.Tests.Ports;

public sealed class ImageGenerationPortSmallTests
{
    [Fact(Skip = "TODO: Implement with the first ImageGenerationPort implementation.")]
    public void ImageGenerationPort_Generate_WhenRequestIsValid_ReturnsGeneratedImageData()
    {
        // ID: PORT-01
        // Source: docs/v1/api/ports.md §2 and §4.
        // Given: a validated ImageGenerationRequest and a controlled successful Port implementation
        // When: image generation is requested through ImageGenerationPort
        // Then: the Port returns GeneratedImageData containing the generated bytes and media type
        // Blocked by: feature/add-glyph-forge-adapter must provide the first observable Port implementation
        // Priority: High
    }

    [Fact(Skip = "TODO: Implement with the first ImageGenerationPort implementation.")]
    public void ImageGenerationPort_Generate_WhenGenerationFails_ReturnsClassifiedPortError()
    {
        // ID: PORT-02
        // Source: docs/v1/api/ports.md §3-4.
        // Given: a validated ImageGenerationRequest and each failure condition in turn (Theory candidate)
        // When: image generation is requested through ImageGenerationPort
        // Then: the Port returns RATE_LIMITED, TIMEOUT, UNAVAILABLE, INVALID_RESPONSE, or FAILED for the corresponding condition
        // Error: preserve a safe retryAfter value only when its retry period can be determined
        // Blocked by: feature/add-glyph-forge-adapter must provide the first observable Port implementation
        // Priority: High
    }
}
